### PR TITLE
LazyMaths: overload sum method with multiple axes

### PR DESCRIPTION
**Pull request by tschoonj**
Also: original sum method is now invoking Dataset.sum when dealing with
an instance of Dataset...

Signed-off-by: Tom Schoonjans <Tom.Schoonjans@diamond.ac.uk>

### CODE REVIEW

**Comment by jonahkichwacoders** [comment]
@PeterC-DLS This is one for you.

**Comment by PeterC-DLS** [comment]
Please add unit tests for the new methods

**Comment by tschoonj** [comment]
The unit tests are on my to-do pile...

**Comment by tschoonj** [comment]
Thanks!

**Pull request merged**
