### PR TITLE
Remove form and geometry plugins from build

### PR DESCRIPTION
**Pull request by PeterC-DLS**

### CODE REVIEW

**Comment by PeterC-DLS** [comment]
@jonahkichwacoders, @gerring, @jayjaybillings: okay?

**Comment by gerring** [comment]
Yes. We should point people in the direction of the binary not the repo if we are going this route because of all those unnecessary dependencies.

**Comment by jayjaybillings** [comment]
@gerring I think some stuff got in there that shouldn't. Like I said, I'll take a look at it.

@PeterC-DLS Looks good to me.

**Comment by jayjaybillings** [comment]
Can I press the big green button now or are we waiting on another review?

**Comment by jonahkichwacoders** [comment]
> Can I press the big green button now or are we waiting on another review?

Yes you can, and no more reviews needed, but as I was looking I did a review too.

**Pull request merged**
