### PR TITLE
Removed references to ICE

### PR DESCRIPTION
**Pull request by SmithRWORNL**
Renamed several classes and packages which were still references ICE and
cleaned up the documentation to refer to January instead of ICE in response to #170.

Signed-off-by: Robert Smith <smithrw@ornl.gov>

### CODE REVIEW

**Comment by jayjaybillings** [comment]
@SmithRWORNL Does this build for you? I'll give it a go shortly.

**Comment by SmithRWORNL** [comment]
@jayjaybillings I believe it did, yes.

**Comment by jonahkichwacoders** [comment]
This was closed as a side-effect of deleting the forms branch. Please resubmit it against https://github.com/eclipse/january-forms master branch.

**Comment by jayjaybillings** [comment]
Closing since this code has been moved to a new repo.

**Comment by jayjaybillings** [comment]
@SmithRWORNL resubmitted it and I just merged it.

**Pull request closed without merging**
