### PR TITLE
Lower Java requirement to 1.6

### PR DESCRIPTION
**Pull request by PeterC-DLS**

### CODE REVIEW

**Comment by jonahkichwacoders** [comment]
Have you checked if this change builds Java 6 jar files? The classpaths and jdt settings also need updating for the change to be proper. For example it needs to be an error to use APIs added to standard library in 1.8, which requires that a 1.6 JDK is installed to run the build against.

**Comment by jonahkichwacoders** [comment]
I think among other things that means the travis yaml file needs updating and the ci.eclipse.org/january configuration needs updating too.

**Comment by PeterC-DLS** [comment]
I didn't think it was as simple as this commit. I will look into further.

**Comment by gerring** [comment]
Oh blimey they can...

**Comment by jonahkichwacoders** [comment]
@gerring @PeterC-DLS interesting I didn't get a notification of the new commits because it was a force push even though I was a reviewer. I did get notifications of Matt's approval. 

I am fine with this as is, the resulting class files are indeed version 50 (instead of 52). 

There is an outstanding issue that because code is compiled with JDK 8, that any use of Java 8 library will not be flagged up. As an example I submitted PR #93 that shows travis is happy although I added a call to Long.compareUnsigned in the code. So as long as before release someone is running on their dev machine with a 1.6 JDK, we should be ok.

If you don't have a 1.6 JDK installed, you should have this warning for each project: *Build path specifies execution environment JavaSE-1.6. There are no JREs installed in the workspace that are strictly compatible with this environment.*

There are ways with non-Tycho maven projects to check, see the notes at the end of https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html

**Comment by jonahkichwacoders** [comment]
PS this change introduces an error on o.e.j.asserts/build.properties: javacProjectSettings = true It seems to have something to do with all the changes in org.eclipse.jdt.core.prefs. Were those other changes intentional?

**Comment by jonahkichwacoders** [comment]
https://eclipse.org/tycho/sitedocs/tycho-compiler-plugin/compile-mojo.html#useJDK seems to indicate that setting the toolchains.xml up properly will solve the library problem.

**Comment by gerring** [comment]
If only someone had suggested removing forced push (joking). Joking apart,
yes I have never used toolchains.xml, looks interesting.

**Comment by PeterC-DLS** [comment]
I noticed this in master and have a commit to tidy up the build.properties and jdt.core.prefs

Will push my changes soon.

Regards,
Peter

**Comment by PeterC-DLS** [comment]
@johankichwacoders Switching to Tycho 0.22.0 gives us a successful build!

**Pull request closed without merging**
