### PR TITLE
Suggested simplification of project to remove xtext and forms.

### PR DESCRIPTION
**Pull request by gerring**
Do not merge this yet, need to get agreement from everyone on the project and to ensure that the bundles are available in ICE.

This change will probably need some build tweaks to work which I have not yet included.

### CODE REVIEW

**Comment by jonahkichwacoders** [comment]
This is (as expected) in conflict with PR #28 At the moment that PR tries to address issues #25 and #26, however at the moment it has been such a long time on both of those issues (early nov and early dec)  and they are not resolved, at the moment my vote would be to pull these things (geometry and form) out now, and consider adding them back in at a later date when they are more mature and meet the original goals of this project of being a non-UI library.

AFAIK There is no need to wait on EAVP or ICE as they are still not consuming from January.

**Comment by PeterC-DLS** [comment]
From @jonahkichwacoders 's comments, EAVP or ICE does not use January at the moment, right?

I am willing to okay this if @jayjaybillings has no objections.

**Comment by jayjaybillings** [comment]
I'll comment on the email thread.

**Comment by gerring** [comment]
I think we are in agreement to ok this and it will be merged some time between 15:00 and 16:00 GMT unless someone throws a black ball at me...

**Comment by gerring** [comment]
I don't understand the comments on the email thread under january. They do not seem to be addressing the dependency issues and are talking about something else to do with ICE I think...

**Pull request merged**
