### PR TITLE
Build workaround

### PR DESCRIPTION
**Pull request by IanMayo**
This isn't a permanent fix. It's Ian's workaround to get the metadata test class to work.

### CODE REVIEW

**Comment by IanMayo** [comment]
Sorry guys, this PR was meant to be created against a fork of January. Deleting.

**Comment by IanMayo** [comment]
Sorry @gerring - this isn't meant to be a valid PR. It manually pulls in the classes necessary for my team to further explore support for Units of Measurement in January.  Once our exploration has progressed the *tidy* solution will be to update the january examples *.target* file.  But, we don't want to divert our attentions down that rabbit-hole right now.

Consequently, @PeterC-DLS is welcome to delete this PR, permissions allowing.

**Comment by jonahkichwacoders** [comment]
PRs can't be deleted except in exceptional circumstances and require contacting github support.

**Comment by IanMayo** [comment]
@jonahkichwacoders - I've sent the request.  I'm not optimistic.

**Comment by jayjaybillings** [comment]
Isn't it enough that it is closed?

Sent from my iPad

On Jan 6, 2017, at 8:19 AM, Ian Mayo <notifications@github.com<mailto:notifications@github.com>> wrote:


@jonahkichwacoders<https://github.com/jonahkichwacoders> - I've sent the request. I'm not optimistic.

-

**Pull request closed without merging**
