### PR TITLE
Add unit metadata2

### PR DESCRIPTION
**Pull request by PeterC-DLS**

### CODE REVIEW

**Comment by belkassaby** [comment]
the target and tpd files need to have their orbit location updated with : 
      <repository id="eclipse-orbit-neon-sr3" location="http://download.eclipse.org/tools/orbit/downloads/drops/R20170307180635/repository"/>

**Comment by belkassaby** [comment]
#258 is the updated pull request... however the ip-validation is still failing... this might be due to the merge and in my last commit I should have added noreply@github as a committer too... Will try to sort that out tomorrow...

**Comment by belkassaby** [comment]
could you update this pull request with my latest commits in #259 ? once more an ip-validation failure...

**Comment by PeterC-DLS** [comment]
Closes #72

**Pull request merged**
