### PR TITLE
Example PR showing eclipse ip-validation failure

### PR DESCRIPTION
**Pull request by jonahgraham**

### CODE REVIEW

**Comment by jonahkichwacoders** [comment]
Re-creating PR as I want to preserve this failing ip-validation as AFAICT it is wrong.

**Comment by jonahkichwacoders** [comment]
Hmm, with PR closed the checks disappear. Re-opening.

This does not need to be merged, it is replaced by #151

**Comment by jonahkichwacoders** [comment]
Bug reported https://bugs.eclipse.org/bugs/show_bug.cgi?id=514758

**Comment by PeterC-DLS** [comment]
Closing this as ECA has been rewritten: https://bugs.eclipse.org/bugs/show_bug.cgi?id=540694

**Pull request closed without merging**
