### PR TITLE
Forms branch update

### PR DESCRIPTION
**Pull request by SmithRWORNL**
Updated and reorganized the geometry packages.

### CODE REVIEW

**Comment by jayjaybillings** [comment]
I'm not sure where the noreply@github.com thing is coming in from the ip-validation. Any thoughts anyone?

**Comment by jayjaybillings** [comment]
I can't find noreply@github.com in any of the logs. Since that is the only other problem with IP and it doesn't explicitly say that you missed something, then I would vote that we not worry about that, especially since you are covered under an MLA. Also, since you are covered under an MLA we don't need to put this in for a CQ (it is covered by scenario 2 in the IP guidelines). However, I leave this decision up to @jonahkichwacoders and @PeterC-DLS since it is their project.

I'm running the build now and...

```
[INFO] Building The Eclipse January Project 2.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ org.eclipse.january.root ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] org.eclipse.january.releng ......................... SUCCESS [  0.041 s]
[INFO] org.eclipse.january.geometry.model ................. SUCCESS [  2.132 s]
[INFO] org.eclipse.january.form ........................... SUCCESS [  0.600 s]
[INFO] org.eclipse.january.form.feature ................... SUCCESS [  0.160 s]
[INFO] org.eclipse.january.form.test ...................... SUCCESS [ 18.133 s]
[INFO] org.eclipse.january.geometry.model.tests ........... SUCCESS [  3.942 s]
[INFO] org.eclipse.january.geometry.dsl.iges .............. SUCCESS [  0.570 s]
[INFO] org.eclipse.january.test.geometry.dsl.iges ......... SUCCESS [  2.515 s]
[INFO] org.eclipse.january.geometry.dsl.mtl ............... SUCCESS [  0.533 s]
[INFO] org.eclipse.january.geometry.dsl.obj ............... SUCCESS [  0.284 s]
[INFO] org.eclipse.january.test.geometry.dsl.obj .......... SUCCESS [  0.189 s]
[INFO] org.eclipse.january.geometry.dsl.stl ............... SUCCESS [  0.253 s]
[INFO] org.eclipse.january.geometry.dsl.vtk ............... SUCCESS [  0.416 s]
[INFO] org.eclipse.january.test.geometry.dsl.vtk .......... SUCCESS [  3.311 s]
[INFO] org.eclipse.january.releng.target .................. SUCCESS [  0.005 s]
[INFO] org.eclipse.january.releng.p2 ...................... SUCCESS [  1.813 s]
[INFO] The Eclipse January Project ........................ SUCCESS [  0.020 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 58.188 s
[INFO] Finished at: 2017-04-12T16:11:41-04:00
[INFO] Final Memory: 133M/1270M
[INFO] ------------------------------------------------------------------------
```

The problem with Travis is that it does not have the test files from the JanuaryTests repo at github.com/jonahkichwacoders/JanuaryTests.

**Comment by jayjaybillings** [comment]
@SmithRWORNL I notice that you left the vtk.ui, vtk.ide, and model.ide bundles in here. Didn't we plan to keep all of those UI bundles in EAVP?

**Comment by jayjaybillings** [comment]
I just spoke to @SmithRWORNL on his way out and he said he will delete the vtk.ui, vtk.ui.tests, vtk.ide and model.ide bundles tomorrow. Note that the model.ide bundle is actually empty, so it is probably just an artifact.

I'm not sure that we can keep UI and IDE bundles in EAVP or ICE if we change the package names to match those projects' naming schemes. I don't think the XText generators would be able to handle it and I doubt the code would compile or run (postulated with no proof of course). If that is the case, what might be necessary is the following. January keeps...
* j.form
* j.form.feature
* j.form.test
* j.geometry.model
* j.geometry.model.tests

EAVP keeps...
* \*.geometry.dsl.\* - so that we don't have problems with EMF and Xtext trying to deal with j.g.dsl.* and eavp.g.dsl.*.{ui,ide}.

@SmithRWORNL also said that he would test that tomorrow.

**Comment by jonahkichwacoders** [comment]
I have not reviewed in detail, but there are some things that need to be resolved. Most critically is there are some packages that are misnamed. This is the quick git grep I did:


```
$ git grep '^package' | cut -f2 -d: | grep -v 'org.eclipse'
package dsl.ide.contentassist.antlr;
package dsl.ide.contentassist.antlr;
package xtext.ide.contentassist.antlr.internal;
package xtext.ide.contentassist.antlr.internal;
package dsl.ide.contentassist.antlr.internal;
package dsl.ide.contentassist.antlr.internal;
package xtext;
package xtext;
package xtext.parser.antlr;
package xtext.parser.antlr;
package xtext.parser.antlr.internal;
package xtext.parser.antlr.internal;
package xtext.parser.antlr.internal;
package xtext.parser.antlr.internal;
package xtext.scoping;
package xtext.serializer;
package xtext.serializer;
package xtext.services;
package xtext.validation;
package xtext
package xtext
package xtext.formatting;
package xtext.generator
package xtext.scoping
package xtext.validation
package xtext;
package xtext;
package xtext.generator;
package xtext.scoping;
package xtext.validation;
```

**Comment by jayjaybillings** [comment]
@SmithRWORNL - Here's a list with file names.:
```
org.eclipse.january.geometry.dsl.stl/src-gen/dsl/ide/contentassist/antlr/internal/InternalSTL.g:package xtext.ide.contentassist.antlr.internal;
org.eclipse.january.geometry.dsl.stl/src-gen/dsl/ide/contentassist/antlr/internal/InternalSTL.g:package xtext.ide.contentassist.antlr.internal;
org.eclipse.january.geometry.model/src-gen/xtext/AbstractSTLRuntimeModule.java:package xtext;
org.eclipse.january.geometry.model/src-gen/xtext/STLStandaloneSetupGenerated.java:package xtext;
org.eclipse.january.geometry.model/src-gen/xtext/parser/antlr/STLAntlrTokenFileProvider.java:package xtext.parser.antlr;
org.eclipse.january.geometry.model/src-gen/xtext/parser/antlr/STLParser.java:package xtext.parser.antlr;
org.eclipse.january.geometry.model/src-gen/xtext/parser/antlr/internal/InternalSTL.g:package xtext.parser.antlr.internal;
org.eclipse.january.geometry.model/src-gen/xtext/parser/antlr/internal/InternalSTL.g:package xtext.parser.antlr.internal;
org.eclipse.january.geometry.model/src-gen/xtext/parser/antlr/internal/InternalSTLLexer.java:package xtext.parser.antlr.internal;
org.eclipse.january.geometry.model/src-gen/xtext/parser/antlr/internal/InternalSTLParser.java:package xtext.parser.antlr.internal;
org.eclipse.january.geometry.model/src-gen/xtext/scoping/AbstractSTLScopeProvider.java:package xtext.scoping;
org.eclipse.january.geometry.model/src-gen/xtext/serializer/STLSemanticSequencer.java:package xtext.serializer;
org.eclipse.january.geometry.model/src-gen/xtext/serializer/STLSyntacticSequencer.java:package xtext.serializer;
org.eclipse.january.geometry.model/src-gen/xtext/services/STLGrammarAccess.java:package xtext.services;
org.eclipse.january.geometry.model/src-gen/xtext/validation/AbstractSTLValidator.java:package xtext.validation;
org.eclipse.january.geometry.model/src/xtext/STLRuntimeModule.xtend:package xtext
org.eclipse.january.geometry.model/src/xtext/STLStandaloneSetup.xtend:package xtext
org.eclipse.january.geometry.model/src/xtext/formatting/STLFormatter.java:package xtext.formatting;
org.eclipse.january.geometry.model/src/xtext/generator/STLGenerator.xtend:package xtext.generator
org.eclipse.january.geometry.model/src/xtext/scoping/STLScopeProvider.xtend:package xtext.scoping
org.eclipse.january.geometry.model/src/xtext/validation/STLValidator.xtend:package xtext.validation
org.eclipse.january.geometry.model/xtend-gen/xtext/STLRuntimeModule.java:package xtext;
org.eclipse.january.geometry.model/xtend-gen/xtext/STLStandaloneSetup.java:package xtext;
org.eclipse.january.geometry.model/xtend-gen/xtext/generator/STLGenerator.java:package xtext.generator;
org.eclipse.january.geometry.model/xtend-gen/xtext/scoping/STLScopeProvider.java:package xtext.scoping;
org.eclipse.january.geometry.model/xtend-gen/xtext/validation/STLValidator.java:package xtext.validation;
```
Good catch @jonahkichwacoders! I'm saving that script!

**Comment by SmithRWORNL** [comment]
@jayjaybillings I removed the folders for the old bundles and changed the grammar name from xtext to o.e.j.geometry.model.

As for splitting the package, we can just run the mwe2 script, then go to the automatically generated o.e.january.*.ide or .ui package and change all the names and references to o.e.eavp.*.ide, and it seems to find everything even with a different package name.

**Comment by jayjaybillings** [comment]
Thanks @SmithRWORNL.

@jonahkichwacoders I've checked the build and verified that all of these xtext pieces were removed. This looks good to me. I'm inclined to accept it an fix any other issues in separate pull requests. Thoughts?

**Comment by jonahkichwacoders** [comment]
@jayjaybillings I agree. I am merging as is and we can work through remaining issues as separate PRs/etc.

**Pull request merged**
